### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by THERAD1** [NAMELESS-AOSP-OPENSOURCE/manifest#2]

**Comment by clhexftw** [comment]
> Dude why be an ass about this? Are you 12? So immature.

https://www.fsf.org/

**Comment by NAMELESS-AOSP-OPENSOURCE** [comment]
> Dude why be an ass about this? Are you 12? So immature.

who said im 12 lmao, are you 12??

**Comment by THERAD1** [comment]
I asked you, no one had to say it. The thing your doing here shows the maturity of a child, so I ask you again why?

**Comment by THERAD1** [comment]
Make me understand the dick move is all I'm asking here...

**Comment by AnierinBliss** [comment]
LMAO 🤣

**Comment by THERAD1** [comment]
> LMAO rofl

What the fuck are you laughing about? You approve of this garbage ? I thought you were respectful dude

**Comment by AnierinBliss** [comment]
> > LMAO rofl
> 
> What the fuck are you laughing about? You approve of this garbage ? I thought you were respectful dude

Laughing at the situation. Sorry, but I don't respect ROMs who close source their entire project all while using other ROM's work which is open to the public. Situations like this are bound to happen - Derp ROM all over again.

Cope + get ratioed + seethe

**Comment by sw5ciprl** [comment]
@THERAD1 you look like you need a haircut my jap + fanatic + hentai fan + -10 iq lover

**Comment by THERAD1** [comment]
The fuck are you laughing at? You approve of this shit?

**Comment by sw5ciprl** [comment]
> The fuck are you laughing at? You approve of this shit?
> […](#)

skill issue
